project:
  type: website
  output-dir: _site

editor: visual

website:
  # title: ""
  favicon: "images/photo_circulo.png"
  cookie-consent:
    type: express
    style: simple 
    palette: light 
  site-url: https://kaiquealves.netlify.app
  page-navigation: true
  open-graph: true
  twitter-card: true
  search: 
    location: navbar
    type: textbox
  navbar:
    background: light
    collapse-below: lg
    title: false
    search: true
    logo: "images/logo.png"
    left:
      - text: "Home"
        file: index.qmd
      - publications.qmd
      - resources.qmd
      - docs/blog/index.qmd
      - about.qmd
      
      
    right:
      - icon: twitter
        href: https://twitter.com/alvesks_
        aria-label: My Twitter
      - icon: github
        href: https://github.com/AlvesKS
        aria-label: My GitHub
      
    tools:
      # - icon: twitter
      #   href: https://twitter.com/AlvesKS_
      # - icon: github
      #   href: https://github.com/AlvesKS
  page-footer: "This website was created and is maintained by Kaique S. Alves 2022" 
  
format:
  html:
    toc: true
    theme: cosmo
    css: styles.css
  
  
theme:
  light: flatly
  dark: darkly